apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-container
          image: nginx:latest
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: example-storage
      volumes:
        - name: example-storage
          persistentVolumeClaim:
            claimName: example-pvc
